// ── package styles ──────────────────────────────────────────────────────
// Injected at materialization time so the client module system's
// claimStyles() tags this <style> with data-plugin and removes it with
// the plugin on teardown/HMR.
if (typeof document !== "undefined" && document.getElementById("dsh-md-annotator-style") === null) {
  const styleEl = document.createElement("style")
  styleEl.id = "dsh-md-annotator-style"
  styleEl.textContent = [
    ".mdan-root{position:relative;display:flex;flex-direction:column;flex:1;min-height:0;padding:10px 12px 0;font-size:13px;line-height:1.7;color:var(--dsw-alias-label-primary)}",
    ".mdan-source-editor{flex:1;min-height:0;width:100%;box-sizing:border-box;padding:12px;border:1px solid var(--dsw-alias-border-l1);border-radius:6px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;resize:none;outline:none;tab-size:2}",
    ".mdan-source-editor:focus{border-color:var(--dsw-alias-brand-primary)}",
    ".mdan-source-status{flex:none;padding:5px 0;font-size:11px;color:var(--dsw-alias-label-secondary)}",
    ".mdan-scroll{position:relative;flex:1;min-height:0;overflow-y:auto}",
    ".mdan-selpick{position:absolute;z-index:5;padding:2px 10px;font-size:12px;line-height:20px;border:1px solid var(--dsw-alias-brand-primary);border-radius:10px;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-brand-primary);cursor:pointer;white-space:nowrap;box-shadow:0 2px 8px rgba(0,0,0,.15)}",
    ".mdan-selpick:hover{background:var(--dsw-alias-bg-layer-2)}",
    "::highlight(mdan-sel){background:rgba(245,158,11,.28)}",
    ".mdan-loading,.mdan-empty{padding:20px 8px;color:var(--dsw-alias-label-secondary);text-align:center}",
    ".mdan-banner{padding:6px 10px;margin-bottom:8px;border-radius:6px;border:1px solid var(--dsw-alias-state-warn-primary);color:var(--dsw-alias-state-warn-primary);font-size:12px}",
    ".mdan-block{position:relative;margin:4px 0;padding:4px 36px 4px 10px;border-left:2px solid transparent;border-radius:6px}",
    ".mdan-block:hover{background:var(--dsw-alias-bg-layer-1)}",
    ".mdan-block-annotated{border-left-color:var(--dsw-alias-state-warn-primary);background:var(--dsw-alias-bg-layer-1)}",
    ".mdan-content{display:block}",
    ".mdan-add{display:none;position:absolute;right:6px;top:2px;padding:1px 8px;font-size:11px;line-height:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-label-secondary);cursor:pointer;white-space:nowrap}",
    ".mdan-add:hover{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
    ".mdan-li:hover>.mdan-add,.mdan-block:hover>.mdan-add{display:inline-block}",
    // 入口互斥：文字选区 pending 或编辑器打开时，隐藏块级 hover 按钮
    ".mdan-root.mdan-selecting .mdan-add,.mdan-root.mdan-editing .mdan-add{display:none!important}",
    ".mdan-add-small{padding:0 6px}",
    ".mdan-count{position:absolute;right:6px;top:28px;min-width:16px;padding:0 4px;font-size:10px;line-height:16px;text-align:center;border-radius:8px;background:var(--dsw-alias-state-warn-primary);color:var(--dsw-alias-bg-base)}",
    ".mdan-count-small{right:2px;top:0}",
    ".mdan-notes{margin-top:6px;display:flex;flex-direction:column;gap:4px}",
    ".mdan-note{display:flex;align-items:flex-start;gap:6px;padding:4px 8px;border-radius:6px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l1);font-size:12px}",
    ".mdan-note-sel{border-left:2px solid var(--dsw-alias-state-warn-primary)}",
    ".mdan-note-text{flex:1;min-width:0;white-space:pre-wrap;word-break:break-word}",
    ".mdan-note-quote{font-size:11px;color:var(--dsw-alias-label-secondary);margin-bottom:2px;white-space:pre-wrap;word-break:break-word}",
    ".mdan-editor-sel{font-size:11px;color:var(--dsw-alias-state-warn-primary);margin-bottom:6px;white-space:pre-wrap;word-break:break-word}",
    ".mdan-note-btn{flex:none;padding:0 6px;font-size:11px;line-height:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}",
    ".mdan-note-btn:hover{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
    ".mdan-editor{margin-top:6px;padding:8px;border:1px solid var(--dsw-alias-brand-primary);border-radius:8px;background:var(--dsw-alias-bg-layer-2)}",
    ".mdan-editor-input{width:100%;min-height:56px;box-sizing:border-box;padding:6px 8px;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:inherit;resize:vertical;outline:none}",
    ".mdan-editor-input:focus{border-color:var(--dsw-alias-brand-primary)}",
    ".mdan-editor-actions{display:flex;justify-content:flex-end;gap:6px;margin-top:6px}",
    ".mdan-btn{padding:2px 10px;font-size:12px;line-height:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:var(--dsw-alias-label-primary);cursor:pointer}",
    ".mdan-btn:disabled{opacity:.45;cursor:not-allowed}",
    ".mdan-btn-primary{border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}",
    ".mdan-btn-primary:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2)}",
    ".mdan-p{margin:4px 0}",
    ".mdan-h1,.mdan-h2,.mdan-h3,.mdan-h4,.mdan-h5,.mdan-h6{margin:10px 0 4px;font-weight:600;line-height:1.4}",
    ".mdan-h1{font-size:19px}.mdan-h2{font-size:17px}.mdan-h3{font-size:15px}.mdan-h4{font-size:14px}.mdan-h5{font-size:13px}.mdan-h6{font-size:12px;color:var(--dsw-alias-label-secondary)}",
    ".mdan-inline-code{padding:1px 4px;background:var(--dsw-alias-bg-layer-2);border-radius:4px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px}",
    ".mdan-code{margin:6px 0;padding:8px 10px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l1);border-radius:6px;overflow-x:auto;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.5}",
    ".mdan-code-lang{font-size:10px;color:var(--dsw-alias-label-secondary);margin-bottom:4px}",
    ".mdan-quote{margin:6px 0;padding:4px 10px;border-left:3px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary)}",
    ".mdan-list{margin:4px 0;padding-left:22px}",
    ".mdan-li{position:relative;padding:2px 26px 2px 2px;border-radius:4px}",
    ".mdan-li:hover{background:var(--dsw-alias-bg-layer-2)}",
    ".mdan-li-annotated{border-left:2px solid var(--dsw-alias-state-warn-primary);padding-left:6px}",
    ".mdan-link{color:var(--dsw-alias-brand-primary);text-decoration:none;cursor:pointer}",
    ".mdan-hr{border:none;border-top:1px solid var(--dsw-alias-border-l1);margin:10px 0}",
    ".mdan-table{border-collapse:collapse;margin:6px 0;width:100%}",
    ".mdan-table th,.mdan-table td{border:1px solid var(--dsw-alias-border-l1);padding:3px 8px;text-align:left;vertical-align:top}",
    ".mdan-table th{background:var(--dsw-alias-bg-layer-2)}",
    ".mdan-panel{position:fixed;z-index:60;display:flex;flex-direction:column;background:var(--dsw-alias-bg-overlay);background:color-mix(in srgb,var(--dsw-alias-bg-overlay) 55%,transparent);-webkit-backdrop-filter:blur(12px);backdrop-filter:blur(12px);border:1px solid var(--dsw-alias-border-l2);border-radius:8px;box-shadow:0 8px 24px rgba(0,0,0,.18);overflow:hidden}",
    ".mdan-panel-head{display:flex;align-items:center;gap:6px;padding:6px 8px;border-bottom:1px solid var(--dsw-alias-border-l1);cursor:move;user-select:none;touch-action:none;background:var(--dsw-alias-bg-layer-2);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 40%,transparent)}",
    ".mdan-panel-title{flex:1;font-size:12px;color:var(--dsw-alias-label-secondary);cursor:move}",
    ".mdan-panel-body{flex:1;min-height:0;overflow-y:auto;padding:6px}",
    ".mdan-panel-resize{position:absolute;right:0;bottom:0;width:18px;height:18px;cursor:nwse-resize;touch-action:none}",
    ".mdan-panel-resize::after{content:'';position:absolute;right:4px;bottom:4px;width:8px;height:8px;border-right:2px solid var(--dsw-alias-border-l2);border-bottom:2px solid var(--dsw-alias-border-l2)}",
    ".mdan-row{display:flex;align-items:flex-start;gap:6px;padding:6px 4px;border-bottom:1px solid var(--dsw-alias-border-l1)}",
    ".mdan-row:last-child{border-bottom:none}",
    ".mdan-row-check{flex:none;margin-top:3px;cursor:pointer}",
    ".mdan-icon-btn{flex:none;min-width:22px;padding:0 5px;font-size:13px;line-height:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}",
    ".mdan-icon-btn:hover:not(:disabled){color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
    ".mdan-icon-btn:disabled{opacity:.45;cursor:not-allowed}",
    ".mdan-row-jump{flex:none;min-width:22px;padding:0 4px;font-size:12px;line-height:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-brand-primary);cursor:pointer}",
    ".mdan-row-body{flex:1;min-width:0}",
    ".mdan-row-note{font-size:12px;white-space:pre-wrap;word-break:break-word}",
    ".mdan-row-quote{font-size:11px;color:var(--dsw-alias-label-secondary);margin-top:2px;word-break:break-word}",
    ".mdan-bar{display:flex;flex-direction:column;flex:none;margin:10px -12px 0;background:var(--dsw-alias-bg-base);border-top:1px solid var(--dsw-alias-border-l1)}",
    ".mdan-bar-handle{display:flex;align-items:center;justify-content:center;gap:6px;width:100%;padding:2px 0;border:none;background:transparent;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:18px;cursor:pointer}",
    ".mdan-bar-handle:hover{color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-bg-layer-1)}",
    ".mdan-bar-body{display:flex;align-items:center;gap:8px;padding:4px 12px 8px}",
    ".mdan-bar.mdan-bar-collapsed .mdan-bar-body{display:none}",
    ".mdan-bar.mdan-bar-collapsed{margin-top:4px}",
    ".mdan-bar-count{font-size:12px;color:var(--dsw-alias-label-secondary)}",
    ".mdan-feedback{font-size:12px;color:var(--dsw-alias-state-success-primary)}",
    ".mdan-feedback-err{color:var(--dsw-alias-state-error-primary)}",
    ".mdan-kindtag{flex:none;display:inline-block;font-size:10px;line-height:16px;padding:0 6px;border-radius:8px;border:1px solid;white-space:nowrap;margin-bottom:2px}",
    ".mdan-kindtag-must{color:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary)}",
    ".mdan-kindtag-suggest{color:var(--dsw-alias-state-warn-primary);border-color:var(--dsw-alias-state-warn-primary)}",
    ".mdan-kindtag-question{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
    ".mdan-kindpick{display:flex;gap:6px;margin-bottom:6px}",
    ".mdan-kindbtn{flex:none;padding:0 8px;font-size:11px;line-height:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}",
    ".mdan-kindbtn-must.mdan-kindbtn-on{color:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary);background:var(--dsw-alias-bg-layer-1)}",
    ".mdan-kindbtn-suggest.mdan-kindbtn-on{color:var(--dsw-alias-state-warn-primary);border-color:var(--dsw-alias-state-warn-primary);background:var(--dsw-alias-bg-layer-1)}",
    ".mdan-kindbtn-question.mdan-kindbtn-on{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-bg-layer-1)}"
  ].join("\n")
  document.head.appendChild(styleEl)
}
