// dsh-md-annotator client half
//
// A `dsh.client` module in the __ModuleLoader__ factory form. This file is
// GENERATED by scripts/bundle.mjs from lib/src/*.js (no bundler/transpiler,
// plain concatenation) and is served verbatim at
// /plugins/dsh-md-annotator/client.js. It registers a Markdown file viewer
// through the `betterSidebar` service (provided by dsh-better-sidebar) with
// priority 10 — above the built-in markdown viewer (0) — so every .md preview
// in the sidebar becomes a block-level annotation surface. Annotations are
// collected and sent to the current session's composer draft as structured
// file-comment requests.
window.__ModuleLoader__.load({
  id: "dsh-md-annotator",
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" })
    var React = require("react")
    //#region src/styles.js
    // ── package styles ──────────────────────────────────────────────────────
    // Injected at materialization time so the client module system's
    // claimStyles() tags this <style> with data-plugin and removes it with
    // the plugin on teardown/HMR.
    if (typeof document !== "undefined" && document.getElementById("dsh-md-annotator-style") === null) {
      const styleEl = document.createElement("style")
      styleEl.id = "dsh-md-annotator-style"
      styleEl.textContent = [
        ".mdan-root{position:relative;display:flex;flex-direction:column;flex:1;min-height:0;padding:10px 12px 0;font-size:13px;line-height:1.7;color:var(--dsw-alias-label-primary)}",
        ".mdan-scroll{position:relative;flex:1;min-height:0;overflow-y:auto}",
        ".mdan-selpick{position:absolute;z-index:5;padding:2px 10px;font-size:12px;line-height:20px;border:1px solid var(--dsw-alias-brand-primary);border-radius:10px;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-brand-primary);cursor:pointer;white-space:nowrap;box-shadow:0 2px 8px rgba(0,0,0,.15)}",
        ".mdan-selpick:hover{background:var(--dsw-alias-bg-layer-2)}",
        "::highlight(mdan-sel){background:rgba(245,158,11,.28)}",
        ".mdan-loading,.mdan-empty{padding:20px 8px;color:var(--dsw-alias-label-secondary);text-align:center}",
        ".mdan-banner{padding:6px 10px;margin-bottom:8px;border-radius:6px;border:1px solid var(--dsw-alias-state-warn-primary);color:var(--dsw-alias-state-warn-primary);font-size:12px}",
        ".mdan-block{position:relative;margin:4px 0;padding:4px 36px 4px 10px;border-left:2px solid transparent;border-radius:6px}",
        ".mdan-block:hover{background:var(--dsw-alias-bg-layer-1)}",
        ".mdan-block-annotated{border-left-color:var(--dsw-alias-state-warn-primary);background:var(--dsw-alias-bg-layer-1)}",
        ".mdan-content{display:block}",
        ".mdan-add{display:none;position:absolute;right:6px;top:2px;padding:1px 8px;font-size:11px;line-height:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-overlay);color:var(--dsw-alias-label-secondary);cursor:pointer;white-space:nowrap}",
        ".mdan-add:hover{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
        ".mdan-li:hover>.mdan-add,.mdan-block:hover>.mdan-add{display:inline-block}",
        // 入口互斥：文字选区 pending 或编辑器打开时，隐藏块级 hover 按钮
        ".mdan-root.mdan-selecting .mdan-add,.mdan-root.mdan-editing .mdan-add{display:none!important}",
        ".mdan-add-small{padding:0 6px}",
        ".mdan-count{position:absolute;right:6px;top:28px;min-width:16px;padding:0 4px;font-size:10px;line-height:16px;text-align:center;border-radius:8px;background:var(--dsw-alias-state-warn-primary);color:var(--dsw-alias-bg-base)}",
        ".mdan-count-small{right:2px;top:0}",
        ".mdan-notes{margin-top:6px;display:flex;flex-direction:column;gap:4px}",
        ".mdan-note{display:flex;align-items:flex-start;gap:6px;padding:4px 8px;border-radius:6px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l1);font-size:12px}",
        ".mdan-note-sel{border-left:2px solid var(--dsw-alias-state-warn-primary)}",
        ".mdan-note-text{flex:1;min-width:0;white-space:pre-wrap;word-break:break-word}",
        ".mdan-note-quote{font-size:11px;color:var(--dsw-alias-label-secondary);margin-bottom:2px;white-space:pre-wrap;word-break:break-word}",
        ".mdan-editor-sel{font-size:11px;color:var(--dsw-alias-state-warn-primary);margin-bottom:6px;white-space:pre-wrap;word-break:break-word}",
        ".mdan-note-btn{flex:none;padding:0 6px;font-size:11px;line-height:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}",
        ".mdan-note-btn:hover{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
        ".mdan-editor{margin-top:6px;padding:8px;border:1px solid var(--dsw-alias-brand-primary);border-radius:8px;background:var(--dsw-alias-bg-layer-2)}",
        ".mdan-editor-input{width:100%;min-height:56px;box-sizing:border-box;padding:6px 8px;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font:inherit;resize:vertical;outline:none}",
        ".mdan-editor-input:focus{border-color:var(--dsw-alias-brand-primary)}",
        ".mdan-editor-actions{display:flex;justify-content:flex-end;gap:6px;margin-top:6px}",
        ".mdan-btn{padding:2px 10px;font-size:12px;line-height:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:var(--dsw-alias-label-primary);cursor:pointer}",
        ".mdan-btn:disabled{opacity:.45;cursor:not-allowed}",
        ".mdan-btn-primary{border-color:var(--dsw-alias-brand-primary);color:var(--dsw-alias-brand-primary)}",
        ".mdan-btn-primary:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2)}",
        ".mdan-p{margin:4px 0}",
        ".mdan-h1,.mdan-h2,.mdan-h3,.mdan-h4,.mdan-h5,.mdan-h6{margin:10px 0 4px;font-weight:600;line-height:1.4}",
        ".mdan-h1{font-size:19px}.mdan-h2{font-size:17px}.mdan-h3{font-size:15px}.mdan-h4{font-size:14px}.mdan-h5{font-size:13px}.mdan-h6{font-size:12px;color:var(--dsw-alias-label-secondary)}",
        ".mdan-inline-code{padding:1px 4px;background:var(--dsw-alias-bg-layer-2);border-radius:4px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px}",
        ".mdan-code{margin:6px 0;padding:8px 10px;background:var(--dsw-alias-bg-layer-2);border:1px solid var(--dsw-alias-border-l1);border-radius:6px;overflow-x:auto;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.5}",
        ".mdan-code-lang{font-size:10px;color:var(--dsw-alias-label-secondary);margin-bottom:4px}",
        ".mdan-quote{margin:6px 0;padding:4px 10px;border-left:3px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-secondary)}",
        ".mdan-list{margin:4px 0;padding-left:22px}",
        ".mdan-li{position:relative;padding:2px 26px 2px 2px;border-radius:4px}",
        ".mdan-li:hover{background:var(--dsw-alias-bg-layer-2)}",
        ".mdan-li-annotated{border-left:2px solid var(--dsw-alias-state-warn-primary);padding-left:6px}",
        ".mdan-link{color:var(--dsw-alias-brand-primary);text-decoration:none;cursor:pointer}",
        ".mdan-hr{border:none;border-top:1px solid var(--dsw-alias-border-l1);margin:10px 0}",
        ".mdan-table{border-collapse:collapse;margin:6px 0;width:100%}",
        ".mdan-table th,.mdan-table td{border:1px solid var(--dsw-alias-border-l1);padding:3px 8px;text-align:left;vertical-align:top}",
        ".mdan-table th{background:var(--dsw-alias-bg-layer-2)}",
        ".mdan-panel{position:fixed;z-index:60;display:flex;flex-direction:column;background:var(--dsw-alias-bg-overlay);background:color-mix(in srgb,var(--dsw-alias-bg-overlay) 55%,transparent);-webkit-backdrop-filter:blur(12px);backdrop-filter:blur(12px);border:1px solid var(--dsw-alias-border-l2);border-radius:8px;box-shadow:0 8px 24px rgba(0,0,0,.18);overflow:hidden}",
        ".mdan-panel-head{display:flex;align-items:center;gap:6px;padding:6px 8px;border-bottom:1px solid var(--dsw-alias-border-l1);cursor:move;user-select:none;touch-action:none;background:var(--dsw-alias-bg-layer-2);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 40%,transparent)}",
        ".mdan-panel-title{flex:1;font-size:12px;color:var(--dsw-alias-label-secondary);cursor:move}",
        ".mdan-panel-body{flex:1;min-height:0;overflow-y:auto;padding:6px}",
        ".mdan-panel-resize{position:absolute;right:0;bottom:0;width:18px;height:18px;cursor:nwse-resize;touch-action:none}",
        ".mdan-panel-resize::after{content:'';position:absolute;right:4px;bottom:4px;width:8px;height:8px;border-right:2px solid var(--dsw-alias-border-l2);border-bottom:2px solid var(--dsw-alias-border-l2)}",
        ".mdan-row{display:flex;align-items:flex-start;gap:6px;padding:6px 4px;border-bottom:1px solid var(--dsw-alias-border-l1)}",
        ".mdan-row:last-child{border-bottom:none}",
        ".mdan-row-check{flex:none;margin-top:3px;cursor:pointer}",
        ".mdan-icon-btn{flex:none;min-width:22px;padding:0 5px;font-size:13px;line-height:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}",
        ".mdan-icon-btn:hover:not(:disabled){color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
        ".mdan-icon-btn:disabled{opacity:.45;cursor:not-allowed}",
        ".mdan-row-jump{flex:none;min-width:22px;padding:0 4px;font-size:12px;line-height:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-brand-primary);cursor:pointer}",
        ".mdan-row-body{flex:1;min-width:0}",
        ".mdan-row-note{font-size:12px;white-space:pre-wrap;word-break:break-word}",
        ".mdan-row-quote{font-size:11px;color:var(--dsw-alias-label-secondary);margin-top:2px;word-break:break-word}",
        ".mdan-bar{display:flex;flex-direction:column;flex:none;margin:10px -12px 0;background:var(--dsw-alias-bg-base);border-top:1px solid var(--dsw-alias-border-l1)}",
        ".mdan-bar-handle{display:flex;align-items:center;justify-content:center;gap:6px;width:100%;padding:2px 0;border:none;background:transparent;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:18px;cursor:pointer}",
        ".mdan-bar-handle:hover{color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-bg-layer-1)}",
        ".mdan-bar-body{display:flex;align-items:center;gap:8px;padding:4px 12px 8px}",
        ".mdan-bar.mdan-bar-collapsed .mdan-bar-body{display:none}",
        ".mdan-bar.mdan-bar-collapsed{margin-top:4px}",
        ".mdan-bar-count{font-size:12px;color:var(--dsw-alias-label-secondary)}",
        ".mdan-feedback{font-size:12px;color:var(--dsw-alias-state-success-primary)}",
        ".mdan-feedback-err{color:var(--dsw-alias-state-error-primary)}",
        ".mdan-kindtag{flex:none;display:inline-block;font-size:10px;line-height:16px;padding:0 6px;border-radius:8px;border:1px solid;white-space:nowrap;margin-bottom:2px}",
        ".mdan-kindtag-must{color:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary)}",
        ".mdan-kindtag-suggest{color:var(--dsw-alias-state-warn-primary);border-color:var(--dsw-alias-state-warn-primary)}",
        ".mdan-kindtag-question{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary)}",
        ".mdan-kindpick{display:flex;gap:6px;margin-bottom:6px}",
        ".mdan-kindbtn{flex:none;padding:0 8px;font-size:11px;line-height:18px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}",
        ".mdan-kindbtn-must.mdan-kindbtn-on{color:var(--dsw-alias-state-error-primary);border-color:var(--dsw-alias-state-error-primary);background:var(--dsw-alias-bg-layer-1)}",
        ".mdan-kindbtn-suggest.mdan-kindbtn-on{color:var(--dsw-alias-state-warn-primary);border-color:var(--dsw-alias-state-warn-primary);background:var(--dsw-alias-bg-layer-1)}",
        ".mdan-kindbtn-question.mdan-kindbtn-on{color:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);background:var(--dsw-alias-bg-layer-1)}"
      ].join("\n")
      document.head.appendChild(styleEl)
    }
    
    //#endregion
    //#region src/store.js
    // ── annotation store + shared pure helpers ──────────────────────────────
    // Storage is per-activation (created in apply(), passed to the viewer via
    // props) — no module-level singleton. Keys are `sessionId \0 path`; both the
    // annotation list and the per-file panel prefs are bounded (LRU + per-key cap)
    // so memory cannot grow without bound over a long multi-file session.
    
    /**
     * @typedef {Object} Note
     * @property {number} v            schema version (1)
     * @property {string} id           unique note id
     * @property {string} ref          versioned reference (v1:...)
     * @property {string} source       verbatim source text the note quotes
     * @property {number} start        1-based start line
     * @property {number} end          1-based end line (exclusive)
     * @property {string} kind         must | suggest | question
     * @property {string} note         the annotation text
     * @property {number} [selStart]   selection char offset within the content subtree
     * @property {number} [selEnd]     selection char offset (exclusive)
     * @property {string} [selText]    selected text
     * @property {boolean} [stale]     derived: ref no longer matches current source
     */
    
    /**
     * @typedef {Object} Block
     * @property {string} type         heading|paragraph|code|quote|hr|table|list
     * @property {string} source       verbatim source text (list: joined raw lines)
     * @property {number} start        1-based start line
     * @property {number} end          1-based end line (exclusive)
     */
    
    const KIND_LABELS = { must: "必须改", suggest: "建议改", question: "疑问" }
    const KIND_ORDER = ["must", "suggest", "question"]
    const DEFAULT_KIND = "suggest"
    
    function kindLabel(kind) {
      return KIND_LABELS[kind] === undefined ? KIND_LABELS[DEFAULT_KIND] : KIND_LABELS[kind]
    }
    
    function storeKey(sessionId, path) {
      return String(sessionId === undefined || sessionId === null ? "" : sessionId) + "\u0000" + String(path === undefined || path === null ? "" : path)
    }
    
    function truncate(text, max) {
      const s = String(text)
      return s.length <= max ? s : s.slice(0, max) + "…"
    }
    
    function clamp(value, min, max) {
      return Math.min(Math.max(value, min), max)
    }
    
    function newNoteId() {
      if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") return "n" + crypto.randomUUID()
      return "n" + Date.now().toString(36) + Math.random().toString(36).slice(2, 7)
    }
    
    // ── ref codec ────────────────────────────────────────────────────────────
    // A note reference is a versioned, content-signed address:
    //   block:  "v1:b:<blockIndex>:<sig8>"
    //   item:   "v1:i:<blockIndex>:<itemIndex>:<sig8>"
    // <sig8> is an 8-hex-char hash of the *context signature* (prev + self + next
    // source), which lets us tell "the same block moved" from "a different block
    // with identical text" after a file regeneration. Legacy refs ("i" or "i:j")
    // are still decoded (version 0) and upgraded on write.
    
    /** FNV-1a 32-bit over a UTF-16 string → 8 hex chars. */
    function hashSource(str) {
      const s = String(str === undefined || str === null ? "" : str)
      let h = 0x811c9dc5
      for (let i = 0; i < s.length; i++) {
        h ^= s.charCodeAt(i)
        h = Math.imul(h, 0x01000193)
      }
      let hex = (h >>> 0).toString(16)
      while (hex.length < 8) hex = "0" + hex
      return hex.slice(0, 8)
    }
    
    function encodeRef(blockIndex, itemIndex, sig) {
      return itemIndex === undefined
        ? "v1:b:" + blockIndex + ":" + sig
        : "v1:i:" + blockIndex + ":" + itemIndex + ":" + sig
    }
    
    /** @returns {{version:number,kind:'b'|'i',index:number,item:number|undefined,sig:string|undefined}|null} */
    function decodeRef(ref) {
      const s = String(ref === undefined || ref === null ? "" : ref)
      const parts = s.split(":")
      if (parts[0] === "v1") {
        if (parts[1] === "b" && parts.length === 4) {
          return { version: 1, kind: "b", index: Number(parts[2]), item: undefined, sig: parts[3] }
        }
        if (parts[1] === "i" && parts.length === 5) {
          return { version: 1, kind: "i", index: Number(parts[2]), item: Number(parts[3]), sig: parts[4] }
        }
        return null
      }
      if (parts.length === 1) return { version: 0, kind: "b", index: Number(parts[0]), item: undefined, sig: undefined }
      if (parts.length === 2) return { version: 0, kind: "i", index: Number(parts[0]), item: Number(parts[1]), sig: undefined }
      return null
    }
    
    function resolveSource(blocks, ref) {
      const d = decodeRef(ref)
      if (d === null) return undefined
      const block = blocks[d.index]
      if (block === undefined) return undefined
      if (d.kind === "i" && block.type === "list" && d.item !== undefined) {
        const item = block.items[d.item]
        return item === undefined ? undefined : item.source
      }
      return block.source
    }
    
    // ── context signatures + re-anchoring ────────────────────────────────────
    
    function blockSigOf(blocks, i) {
      if (i < 0 || i >= blocks.length) return ""
      const b = blocks[i]
      if (b.type === "list") return b.source !== undefined ? b.source : b.items.map((it) => it.source).join("\n")
      return b.source === undefined ? "" : b.source
    }
    
    function contextSignature(blocks, index, itemIndex) {
      if (itemIndex !== undefined) {
        const blk = blocks[index]
        if (blk !== undefined && blk.type === "list") {
          const items = blk.items
          const prev = itemIndex > 0 ? items[itemIndex - 1].source : ""
          const cur = items[itemIndex] === undefined ? "" : items[itemIndex].source
          const next = itemIndex < items.length - 1 ? items[itemIndex + 1].source : ""
          return hashSource(prev + "\u0000" + cur + "\u0000" + next)
        }
        return ""
      }
      return hashSource(blockSigOf(blocks, index - 1) + "\u0000" + blockSigOf(blocks, index) + "\u0000" + blockSigOf(blocks, index + 1))
    }
    
    /** Precompute every block/item context signature once per blocks change. */
    function buildRefIndex(blocks) {
      const blockSigs = new Array(blocks.length)
      const itemSigs = []
      for (let i = 0; i < blocks.length; i++) {
        blockSigs[i] = contextSignature(blocks, i)
        const b = blocks[i]
        if (b.type === "list") {
          const sigs = new Array(b.items.length)
          for (let j = 0; j < b.items.length; j++) sigs[j] = contextSignature(blocks, i, j)
          itemSigs[i] = sigs
        }
      }
      return { blockSigs, itemSigs }
    }
    
    /** Find the single block/item whose source and (when known) context signature
     *  match. Returns {ref,start,end} or null when zero or several candidates — a
     *  conservative choice that never silently mis-anchors to a duplicate. */
    function locateBlockItem(blocks, source, sig, refIndex) {
      const candidates = []
      for (let i = 0; i < blocks.length; i++) {
        const b = blocks[i]
        if (b.type === "list") {
          for (let j = 0; j < b.items.length; j++) {
            if (b.items[j].source === source && (sig === undefined || refIndex.itemSigs[i][j] === sig)) {
              candidates.push({ ref: encodeRef(i, j, refIndex.itemSigs[i][j]), start: b.items[j].start, end: b.items[j].end })
            }
          }
        } else if (b.source === source && (sig === undefined || refIndex.blockSigs[i] === sig)) {
          candidates.push({ ref: encodeRef(i, undefined, refIndex.blockSigs[i]), start: b.start, end: b.end })
        }
      }
      return candidates.length === 1 ? candidates[0] : null
    }
    
    /** Context signature at the position addressed by a decoded ref. */
    function sigAtRef(refIndex, d) {
      if (d.kind === "i" && refIndex.itemSigs[d.index] !== undefined) return refIndex.itemSigs[d.index][d.item]
      return refIndex.blockSigs[d.index]
    }
    
    /**
     * Re-anchor notes against freshly parsed blocks: the addressed index is
     * accepted only when BOTH the source matches AND (for versioned refs) the
     * context signature matches — so a duplicate that slid into the same index is
     * not silently accepted. On mismatch, relocate by (source + signature); fall
     * back to marking stale. Pure and idempotent.
     */
    function reanchorNotes(blocks, notes, refIndex) {
      const index = refIndex === undefined ? buildRefIndex(blocks) : refIndex
      return notes.map((n) => {
        const d = decodeRef(n.ref)
        if (d === null) return Object.assign({}, n, { stale: true })
        if (resolveSource(blocks, n.ref) === n.source) {
          if (d.sig === undefined || sigAtRef(index, d) === d.sig) return Object.assign({}, n, { stale: false })
          // signature mismatch → a different (duplicate) block now sits here; fall through
        }
        const located = locateBlockItem(blocks, n.source, d.sig, index)
        if (located !== null) return Object.assign({}, n, { ref: located.ref, start: located.start, end: located.end, stale: false })
        return Object.assign({}, n, { stale: true })
      })
    }
    
    // ── bounded stores (factory pattern, one instance per activation) ────────
    
    function createAnnotationStore(opts) {
      opts = opts || {}
      const maxKeys = opts.maxKeys || 100
      const maxPerKey = opts.maxPerKey || 500
      const maxNoteLen = opts.maxNoteLen || 2000
      const map = new Map() // key -> { notes, lastAccess }
      let tick = 0
    
      function get(sessionId, path) {
        const key = storeKey(sessionId, path)
        const rec = map.get(key)
        if (rec === undefined) return []
        rec.lastAccess = ++tick
        return rec.notes
      }
      function set(sessionId, path, notes) {
        const key = storeKey(sessionId, path)
        let bounded = notes
        if (notes.length > maxPerKey) {
          console.warn("[dsh-md-annotator] annotation limit reached (" + maxPerKey + "), truncating")
          bounded = notes.slice(0, maxPerKey)
        }
        bounded = bounded.map((n) => {
          const note = Object.assign({ v: 1 }, n)
          if (typeof note.note === "string" && note.note.length > maxNoteLen) note.note = note.note.slice(0, maxNoteLen)
          return note
        })
        map.set(key, { notes: bounded, lastAccess: ++tick })
        evict()
      }
      function clear(sessionId, path) {
        map.delete(storeKey(sessionId, path))
      }
      function evict() {
        while (map.size > maxKeys) {
          let oldestKey = null
          let oldest = Infinity
          map.forEach((rec, k) => { if (rec.lastAccess < oldest) { oldest = rec.lastAccess; oldestKey = k } })
          if (oldestKey === null) break
          map.delete(oldestKey)
        }
      }
      function clearAll() { map.clear() }
      function size() { return map.size }
      return { get, set, clear, clearAll, size }
    }
    
    function createPanelPrefsStore(opts) {
      opts = opts || {}
      const maxKeys = opts.maxKeys || 100
      const map = new Map()
      let tick = 0
    
      function get(sessionId, path) {
        const key = storeKey(sessionId, path)
        const rec = map.get(key)
        if (rec === undefined) return { open: false, barCollapsed: false }
        rec.lastAccess = ++tick
        return rec.prefs
      }
      function set(sessionId, path, prefs) {
        const key = storeKey(sessionId, path)
        map.set(key, { prefs, lastAccess: ++tick })
        while (map.size > maxKeys) {
          let oldestKey = null
          let oldest = Infinity
          map.forEach((rec, k) => { if (rec.lastAccess < oldest) { oldest = rec.lastAccess; oldestKey = k } })
          if (oldestKey === null) break
          map.delete(oldestKey)
        }
      }
      function clear(sessionId, path) { map.delete(storeKey(sessionId, path)) }
      function clearAll() { map.clear() }
      return { get, set, clear, clearAll }
    }
    
    // ── report formatting (pure, unit-testable) ──────────────────────────────
    
    /**
     * @param {Object} opts
     * @param {Note[]} opts.notes
     * @param {string} [opts.prefix]
     * @param {string} opts.pathLabel     e.g. relative path
     * @param {(note:Note)=>string[]} opts.excerptOf  → excerpt lines
     * @param {(note:Note)=>boolean} opts.isStale
     */
    function formatReport(opts) {
      const notes = opts.notes || []
      const prefix = opts.prefix
      const pathLabel = opts.pathLabel || ""
      const excerptOf = opts.excerptOf
      const isStale = opts.isStale
      const out = []
      if (typeof prefix === "string" && prefix.trim() !== "") {
        out.push(prefix.trim())
        out.push("")
      }
      let firstGroup = true
      KIND_ORDER.forEach((kindId) => {
        const group = notes.filter((n) => (typeof n.kind === "string" ? n.kind : DEFAULT_KIND) === kindId)
        if (group.length === 0) return
        if (!firstGroup) out.push("")
        out.push("【" + kindLabel(kindId) + "】")
        out.push("")
        group.forEach((n) => {
          out.push("File: " + pathLabel)
          out.push("Source: markdown")
          out.push("")
          const linesLabel = typeof n.start === "number" && typeof n.end === "number" && n.end > n.start
            ? "Lines " + n.start + "-" + n.end
            : "Line " + (typeof n.start === "number" ? n.start : "?")
          out.push(linesLabel)
          out.push("Excerpt:")
          excerptOf(n).forEach((l) => out.push("> " + l))
          out.push('User comment: "' + n.note + '"')
          if (isStale(n)) out.push("(注：该处内容可能已变化，请按原文定位)")
          out.push("")
        })
        firstGroup = false
      })
      while (out.length > 0 && out[out.length - 1] === "") out.pop()
      return out.join("\n")
    }
    
    //#endregion
    //#region src/parser.js
    // ── markdown block parser + inline renderer ──────────────────────────────
    // Splits markdown source into annotatable blocks. Every block carries the
    // verbatim `source` text plus 1-based `start`/`end` line numbers, used to
    // quote and re-locate it after edits.
    //
    // This is a deliberate CommonMark SUBSET. Not supported (documented in README):
    // setext headings, nested lists (indented children are flattened), inline HTML,
    // list-item code fences/blockquotes, escaped pipes inside table cells.
    
    const LIST_RE = /^\s*([-*+]|\d+[.)])\s+(.*)$/
    const SEP_RE = /^\s*\|?[\s:|-]+\|?\s*$/
    
    function parseBlocks(text) {
      const lines = String(text === undefined || text === null ? "" : text).replace(/\r\n?/g, "\n").split("\n")
      const blocks = []
      let i = 0
      while (i < lines.length) {
        const startLine = i + 1
        const line = lines[i]
        if (/^\s*$/.test(line)) { i++; continue }
        const fence = /^\s{0,3}(`{3,}|~{3,})\s*([\w.+-]*)\s*$/.exec(line)
        if (fence !== null) {
          const marker = fence[1][0]
          const len = fence[1].length
          const lang = fence[2] === undefined ? "" : fence[2]
          const buf = []
          i++
          while (i < lines.length) {
            if (new RegExp("^\\s{0,3}" + marker + "{" + len + ",}\\s*$").test(lines[i])) { i++; break }
            buf.push(lines[i]); i++
          }
          blocks.push({ type: "code", lang: lang, source: buf.join("\n"), start: startLine, end: i })
          continue
        }
        const heading = /^\s{0,3}(#{1,6})\s+(.*)$/.exec(line)
        if (heading !== null) {
          i++
          blocks.push({ type: "heading", level: heading[1].length, source: heading[2].trim(), start: startLine, end: i })
          continue
        }
        if (/^\s{0,3}([-*_])(\s*\1){2,}\s*$/.test(line)) {
          i++
          blocks.push({ type: "hr", source: "", start: startLine, end: i })
          continue
        }
        if (/^\s*>\s?/.test(line)) {
          const quoteBuf = []
          while (i < lines.length && /^\s*>\s?/.test(lines[i])) {
            quoteBuf.push(lines[i].replace(/^\s*>\s?/, ""))
            i++
          }
          blocks.push({ type: "quote", source: quoteBuf.join("\n"), start: startLine, end: i })
          continue
        }
        if (line.indexOf("|") !== -1 && i + 1 < lines.length && lines[i + 1].indexOf("|") !== -1 && SEP_RE.test(lines[i + 1]) && lines[i + 1].indexOf("-") !== -1) {
          const tableBuf = [line]
          i++
          while (i < lines.length && lines[i].indexOf("|") !== -1 && !/^\s*$/.test(lines[i])) {
            tableBuf.push(lines[i]); i++
          }
          blocks.push({ type: "table", source: tableBuf.join("\n"), start: startLine, end: i })
          continue
        }
        const listMatch = LIST_RE.exec(line)
        if (listMatch !== null) {
          const ordered = /^\d/.test(listMatch[1])
          const items = []
          const rawLines = []
          while (i < lines.length) {
            const itemMatch = LIST_RE.exec(lines[i])
            if (itemMatch === null) {
              if (/^\s*$/.test(lines[i])) break
              if (items.length > 0) {
                // continuation line: keep verbatim (preserves code indentation)
                items[items.length - 1].source += "\n" + lines[i]
                items[items.length - 1].end = i + 1
                rawLines.push(lines[i])
              } else break
              i++
              continue
            }
            items.push({ source: itemMatch[2].trim(), start: i + 1, end: i + 1 })
            rawLines.push(lines[i])
            i++
          }
          blocks.push({ type: "list", ordered: ordered, items: items, source: rawLines.join("\n"), start: startLine, end: i })
          continue
        }
        const paraBuf = [line.trim()]
        i++
        while (i < lines.length) {
          const next = lines[i]
          if (/^\s*$/.test(next)) break
          if (/^\s{0,3}#{1,6}\s/.test(next)) break
          if (/^\s{0,3}(`{3,}|~{3,})/.test(next)) break
          if (/^\s{0,3}([-*_])(\s*\1){2,}\s*$/.test(next)) break
          if (/^\s*>\s?/.test(next)) break
          if (LIST_RE.test(next)) break
          if (next.indexOf("|") !== -1 && i + 1 < lines.length && lines[i + 1].indexOf("|") !== -1 && SEP_RE.test(lines[i + 1]) && lines[i + 1].indexOf("-") !== -1) break
          paraBuf.push(next.trim())
          i++
        }
        blocks.push({ type: "paragraph", source: paraBuf.join("\n"), start: startLine, end: i })
      }
      return blocks
    }
    
    // ── inline renderer ─────────────────────────────────────────────────────
    // React-created nodes only (no dangerouslySetInnerHTML): strings are
    // escaped by React itself. Supported: `code`, **bold**, *italic*, ~~del~~,
    // [text](url). Links never navigate (title shows the URL).
    const INLINE_RE = /(`[^`\n]+`|\*\*[^*\n]+\*\*|\*[^*\n]+\*|~~[^~\n]+~~|\[[^\]\n]*\]\([^)\n]*\))/g
    
    function renderInline(text) {
      if (typeof text !== "string" || text === "") return null
      const parts = String(text).split(INLINE_RE)
      const nodes = []
      for (let k = 0; k < parts.length; k++) {
        const part = parts[k]
        if (part === "") continue
        if (k % 2 === 1) {
          if (part.charAt(0) === "`") {
            nodes.push(React.createElement("code", { key: k, className: "mdan-inline-code" }, part.slice(1, -1)))
          } else if (part.indexOf("**") === 0) {
            nodes.push(React.createElement("strong", { key: k }, renderInline(part.slice(2, -2))))
          } else if (part.charAt(0) === "*") {
            nodes.push(React.createElement("em", { key: k }, renderInline(part.slice(1, -1))))
          } else if (part.indexOf("~~") === 0) {
            nodes.push(React.createElement("del", { key: k }, renderInline(part.slice(2, -2))))
          } else if (part.charAt(0) === "[") {
            const linkMatch = /^\[([^\]]*)\]\(([^)]*)\)$/.exec(part)
            const label = linkMatch === null ? part : linkMatch[1]
            const url = linkMatch === null ? "" : linkMatch[2]
            nodes.push(React.createElement("a", {
              key: k,
              className: "mdan-link",
              href: url === "" ? "#" : url,
              title: url === "" ? undefined : url,
              onClick: function (event) { event.preventDefault() }
            }, label))
          }
        } else {
          nodes.push(part)
        }
      }
      return nodes
    }
    
    function parseTable(source) {
      const rows = source.split("\n").filter((l) => l.trim() !== "")
      function splitRow(l) {
        return l.trim().replace(/^\|/, "").replace(/\|$/, "").split("|").map((c) => c.trim())
      }
      const bodyRows = rows.slice(1).filter((l) => !SEP_RE.test(l))
      return { header: rows.length > 0 ? splitRow(rows[0]) : [], body: bodyRows.map(splitRow) }
    }
    
    function blockContent(block) {
      switch (block.type) {
        case "heading":
          return React.createElement("h" + Math.min(block.level, 6), { className: "mdan-h" + Math.min(block.level, 6) }, renderInline(block.source))
        case "paragraph":
          return React.createElement("p", { className: "mdan-p" }, renderInline(block.source))
        case "code":
          return React.createElement("pre", { className: "mdan-code" },
            block.lang !== "" ? React.createElement("div", { className: "mdan-code-lang" }, block.lang) : null,
            React.createElement("code", null, block.source))
        case "quote":
          return React.createElement("blockquote", { className: "mdan-quote" }, renderInline(block.source))
        case "hr":
          return React.createElement("hr", { className: "mdan-hr" })
        case "table": {
          const table = parseTable(block.source)
          return React.createElement("table", { className: "mdan-table" },
            React.createElement("thead", null,
              React.createElement("tr", null, table.header.map((cell, j) => React.createElement("th", { key: j }, renderInline(cell))))),
            React.createElement("tbody", null, table.body.map((row, j) =>
              React.createElement("tr", { key: j }, row.map((cell, k) => React.createElement("td", { key: k }, renderInline(cell)))))))
        }
        case "list":
          return React.createElement(block.ordered ? "ol" : "ul", { className: "mdan-list" },
            block.items.map((item, j) => React.createElement("li", { key: j }, renderInline(item.source))))
        default:
          return null
      }
    }
    
    //#endregion
    //#region src/selection.js
    // ── text-selection helpers ──────────────────────────────────────────────
    // Selection offsets are computed against an annotatable unit's content subtree
    // (the `.mdan-content` element carrying `data-mdan-ref`), so they stay stable
    // across re-renders of the same block source and are never skewed by the
    // control buttons / note chips that live outside that subtree.
    
    function subtreeTextLen(node) {
      if (node.nodeType === 3) return node.data.length
      let total = 0
      let child = node.firstChild
      while (child !== null) { total += subtreeTextLen(child); child = child.nextSibling }
      return total
    }
    
    // (node, offset) boundary → character offset within root's textContent.
    // Handles both text-node offsets and element-node child indexes.
    function boundaryOffset(root, node, offset) {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_ALL, null)
      let count = 0
      let n
      while ((n = walker.nextNode()) !== null) {
        if (n === node) {
          if (n.nodeType === 3) return count + offset
          let child = n.firstChild
          let skipped = 0
          while (child !== null && skipped < offset) { count += subtreeTextLen(child); child = child.nextSibling; skipped++ }
          return count
        }
        if (n.nodeType === 3) count += n.data.length
      }
      return null
    }
    
    // Character offsets within root.textContent → DOM Range spanning them.
    function rangeFromOffsets(root, start, end) {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
      let count = 0
      let t, startNode = null, startOff = 0, endNode = null, endOff = 0
      while ((t = walker.nextNode()) !== null) {
        const len = t.data.length
        if (startNode === null && start <= count + len) { startNode = t; startOff = start - count }
        if (end <= count + len) { endNode = t; endOff = end - count; break }
        count += len
      }
      if (startNode === null || endNode === null) return null
      const r = document.createRange()
      r.setStart(startNode, startOff)
      r.setEnd(endNode, endOff)
      return r
    }
    
    //#endregion
    //#region src/panel.js
    // ── floating panel geometry ─────────────────────────────────────────────
    // Single source of truth for the panel's default/min size and viewport
    // clamping, replacing five scattered copies of the same magic numbers.
    
    const PANEL_DEFAULTS = { w: 360, h: 300 }
    const PANEL_MIN = { w: 240, h: 160 }
    const PANEL_MARGIN = { x: 8, y: 8, keepX: 160, keepY: 48 }
    
    /** Clamp a panel's x/y/w/h back into the viewport, mutating a fresh copy. */
    function clampPanel(prefs, vw, vh) {
      const x = clamp(typeof prefs.x === "number" ? prefs.x : PANEL_MARGIN.x, PANEL_MARGIN.x, Math.max(PANEL_MARGIN.x, vw - PANEL_MARGIN.keepX))
      const y = clamp(typeof prefs.y === "number" ? prefs.y : PANEL_MARGIN.y, PANEL_MARGIN.y, Math.max(PANEL_MARGIN.y, vh - PANEL_MARGIN.keepY))
      const w = clamp(typeof prefs.w === "number" ? prefs.w : PANEL_DEFAULTS.w, PANEL_MIN.w, Math.max(PANEL_MIN.w, vw - x - PANEL_MARGIN.x))
      const h = clamp(typeof prefs.h === "number" ? prefs.h : PANEL_DEFAULTS.h, PANEL_MIN.h, Math.max(PANEL_MIN.h, vh - y - PANEL_MARGIN.y))
      return Object.assign({}, prefs, { x, y, w, h })
    }
    
    //#endregion
    //#region src/viewer.js
    // ── viewer component ────────────────────────────────────────────────────
    // MdAnnotateView renders the parsed blocks as an annotation surface. Render
    // performance is preserved by: (1) isolating the annotation editor into its
    // own component with local draft state, so keystrokes never rebuild the block
    // tree; (2) precomputing a ref→notes Map (O(1) lookups instead of O(B×A)
    // scans); (3) memoizing block/note-list components behind stable callbacks;
    // (4) RAF-throttling panel drag/resize with a single persist on pointerup.
    
    function kindTag(kind) {
      const id = typeof kind === "string" ? kind : DEFAULT_KIND
      return React.createElement("span", { className: "mdan-kindtag mdan-kindtag-" + id }, kindLabel(id))
    }
    
    /** Error boundary: a render-time exception degrades to a recoverable message
     *  instead of tearing down the whole sidebar preview. */
    class MdErrorBoundary extends React.Component {
      constructor(props) {
        super(props)
        this.state = { error: null }
        this.reset = () => this.setState({ error: null })
      }
      static getDerivedStateFromError(error) {
        return { error: error }
      }
      componentDidCatch(error, info) {
        console.error("[dsh-md-annotator] viewer render failed:", error, info && info.componentStack)
      }
      render() {
        if (this.state.error !== null) {
          return React.createElement("div", { className: "mdan-empty" },
            React.createElement("div", null, "该文件预览出错"),
            React.createElement("button", { type: "button", className: "mdan-btn", onClick: this.reset }, "恢复"))
        }
        return this.props.children
      }
    }
    
    /** Isolated annotation editor: draft text lives here, so typing only
     *  re-renders this subtree. Reports save/cancel/kind back up via callbacks. */
    function AnnotationEditor(props) {
      const editing = props.editing
      const draftState = React.useState(editing !== null && typeof editing.initialText === "string" ? editing.initialText : "")
      const draft = draftState[0]
      const setDraft = draftState[1]
      const editorKey = editing === null ? null : (editing.noteId !== undefined ? "edit:" + editing.noteId : "new:" + editing.ref)
      React.useEffect(function () {
        setDraft(editing !== null && typeof editing.initialText === "string" ? editing.initialText : "")
      }, [editorKey])
      if (editing === null) return null
      const kind = typeof editing.kind === "string" ? editing.kind : DEFAULT_KIND
      return React.createElement("div", { className: "mdan-editor" },
        editing.selText !== undefined ? React.createElement("div", { className: "mdan-editor-sel" }, "选中：" + truncate(editing.selText, 120)) : null,
        React.createElement("div", { className: "mdan-kindpick" },
          KIND_ORDER.map(function (kindId) {
            return React.createElement("button", {
              key: kindId,
              type: "button",
              className: "mdan-kindbtn mdan-kindbtn-" + kindId + (kind === kindId ? " mdan-kindbtn-on" : ""),
              onClick: function () { props.onPickKind(kindId) }
            }, kindLabel(kindId))
          })),
        React.createElement("textarea", {
          className: "mdan-editor-input",
          value: draft,
          placeholder: "写下对这一处内容的修改意见…",
          autoFocus: true,
          onChange: function (event) { setDraft(event.target.value) },
          onKeyDown: function (event) {
            if ((event.metaKey || event.ctrlKey) && event.key === "Enter") {
              event.preventDefault()
              props.onSave(draft, kind)
            }
          }
        }),
        React.createElement("div", { className: "mdan-editor-actions" },
          React.createElement("button", { type: "button", className: "mdan-btn mdan-btn-primary", onClick: function () { props.onSave(draft, kind) } }, editing.noteId !== undefined ? "保存修改" : "保存批注"),
          React.createElement("button", { type: "button", className: "mdan-btn", onClick: props.onCancel }, "取消")))
    }
    
    const NoteList = React.memo(function NoteList(props) {
      const notes = props.notes
      return React.createElement("div", { className: "mdan-notes" },
        notes.map(function (n) {
          return React.createElement("div", { key: n.id, className: "mdan-note" + (n.selText !== undefined ? " mdan-note-sel" : "") },
            kindTag(n.kind),
            React.createElement("span", { className: "mdan-note-text" },
              n.selText !== undefined ? React.createElement("div", { className: "mdan-note-quote" }, "「" + truncate(n.selText, 80) + "」") : null,
              n.note),
            React.createElement("button", { type: "button", className: "mdan-note-btn", onClick: function () { props.onEdit(n) } }, "编辑"),
            React.createElement("button", { type: "button", className: "mdan-note-btn", onClick: function () { props.onRemove(n.id) } }, "删除"))
        }))
    })
    
    const MdBlock = React.memo(function MdBlock(props) {
      const block = props.block
      const index = props.index
      const refIndex = props.refIndex
      const editing = props.editing
    
      if (block.type === "list") {
        return React.createElement("div", { className: "mdan-block" },
          React.createElement(block.ordered ? "ol" : "ul", { className: "mdan-list" },
            block.items.map(function (item, j) {
              const itemRef = encodeRef(index, j, refIndex.itemSigs[index][j])
              const itemNotes = props.notesByRef.get(itemRef) || []
              const itemEditing = editing !== null && editing.ref === itemRef
              return React.createElement("li", {
                key: j,
                className: "mdan-li" + (itemNotes.length > 0 ? " mdan-li-annotated" : "")
              },
                React.createElement("span", { className: "mdan-content", "data-mdan-ref": itemRef }, renderInline(item.source)),
                React.createElement("button", { type: "button", className: "mdan-add mdan-add-small", title: "批注此项", "aria-label": "批注此项", onClick: function () { props.onOpenBlock(itemRef, item.source, item.start, item.end) } }, "＋"),
                itemNotes.length > 0 ? React.createElement("span", { className: "mdan-count mdan-count-small" }, String(itemNotes.length)) : null,
                itemNotes.length > 0 ? React.createElement(NoteList, { notes: itemNotes, onEdit: props.onEdit, onRemove: props.onRemove }) : null,
                itemEditing ? React.createElement(AnnotationEditor, { editing: editing, onSave: props.onSave, onCancel: props.onCancel, onPickKind: props.onPickKind }) : null)
            })))
      }
    
      const ref = encodeRef(index, undefined, refIndex.blockSigs[index])
      const notes = props.notes
      const isEditing = editing !== null && editing.ref === ref
      return React.createElement("div", {
        className: "mdan-block" + (notes.length > 0 ? " mdan-block-annotated" : "")
      },
        React.createElement("div", { className: "mdan-content", "data-mdan-ref": ref }, blockContent(block)),
        notes.length > 0 ? React.createElement(NoteList, { notes: notes, onEdit: props.onEdit, onRemove: props.onRemove }) : null,
        React.createElement("button", { type: "button", className: "mdan-add", title: "批注此块", "aria-label": "批注此块", onClick: function () { props.onOpenBlock(ref, block.source, block.start, block.end) } }, "＋ 批注"),
        notes.length > 0 ? React.createElement("span", { className: "mdan-count" }, String(notes.length)) : null,
        isEditing ? React.createElement(AnnotationEditor, { editing: editing, onSave: props.onSave, onCancel: props.onCancel, onPickKind: props.onPickKind }) : null)
    })
    
    function MdAnnotateView(props) {
      const path = props.path
      const sessionId = props.scope === undefined ? undefined : props.scope.sessionId
      const content = props.content
      const annotationStore = props.annotationStore
      const panelPrefsStore = props.panelPrefsStore
    
      const tickState = React.useState(0)
      const tick = tickState[0]
      const setTick = tickState[1]
      const editingState = React.useState(null) // { ref, source, start, end, noteId?, kind, selStart?, selEnd?, selText?, initialText }
      const editing = editingState[0]
      const setEditing = editingState[1]
      const panelState = React.useState(function () { return panelPrefsStore.get(sessionId, path) })
      const panel = panelState[0]
      const setPanel = panelState[1]
      const feedbackState = React.useState(null) // { kind: 'ok'|'err', text, detail? }
      const feedback = feedbackState[0]
      const setFeedback = feedbackState[1]
      const anchorState = React.useState(null)
      const anchor = anchorState[0]
      const setAnchor = anchorState[1]
      const selState = React.useState(null) // { ref, start, end, text, x, y } | null
      const sel = selState[0]
      const setSel = selState[1]
      const selectedState = React.useState([])
      const selectedIds = selectedState[0]
      const setSelectedIds = selectedState[1]
    
      const rootRef = React.useRef(null)
      const scrollRef = React.useRef(null)
      const dragRef = React.useRef(null) // { kind, pointerId, startClientX/Y, baseX/Y/W/H, lastClientX/Y, frame }
      const editingRef = React.useRef(null)
      const selRef = React.useRef(null)
      const panelOpenRef = React.useRef(false)
      const togglePanelRef = React.useRef(null)
      const lastKindRef = React.useRef(DEFAULT_KIND)
      editingRef.current = editing
      selRef.current = sel
      panelOpenRef.current = panel.open === true
    
      const blocks = React.useMemo(function () {
        return parseBlocks(content === undefined ? "" : content)
      }, [content])
      const refIndex = React.useMemo(function () {
        return buildRefIndex(blocks)
      }, [blocks])
      const annotations = React.useMemo(function () {
        return reanchorNotes(blocks, annotationStore.get(sessionId, path), refIndex)
      }, [tick, sessionId, path, blocks, refIndex, annotationStore])
      const notesByRef = React.useMemo(function () {
        const m = new Map()
        annotations.forEach(function (n) {
          const arr = m.get(n.ref)
          if (arr === undefined) m.set(n.ref, [n])
          else arr.push(n)
        })
        return m
      }, [annotations])
      const selectedSet = React.useMemo(function () {
        return new Set(selectedIds)
      }, [selectedIds])
    
      React.useEffect(function () {
        setSelectedIds([])
      }, [sessionId, path])
    
      function persistOrClear(list) {
        if (list.length === 0) annotationStore.clear(sessionId, path)
        else annotationStore.set(sessionId, path, list)
        setTick(function (t) { return t + 1 })
      }
    
      // Read one plugin-owned setting (declared through settings.pluginToggles and
      // persisted by the sidebar under pluginSettings['md-annotator']).
      function pluginSetting(key, fallback) {
        const store = props.store
        try {
          if (store === undefined || typeof store.getPrefs !== "function") return fallback
          const blob = store.getPrefs().pluginSettings
          const mine = blob === undefined || blob === null ? undefined : blob["md-annotator"]
          if (mine !== undefined && mine !== null && mine[key] !== undefined) return mine[key]
        } catch (error) {
          console.debug("[dsh-md-annotator] pluginSetting read failed:", error)
        }
        return fallback
      }
    
      const openEditorCb = React.useCallback(function (ref, source, start, end) {
        setEditing({ ref: ref, source: source, start: start, end: end, kind: lastKindRef.current, initialText: "" })
        setFeedback(null)
      }, [])
      const openEditorForCb = React.useCallback(function (note) {
        setEditing({
          ref: note.ref, source: note.source, start: note.start, end: note.end,
          noteId: note.id, kind: typeof note.kind === "string" ? note.kind : lastKindRef.current,
          selStart: note.selStart, selEnd: note.selEnd, selText: note.selText, initialText: note.note
        })
        setFeedback(null)
      }, [])
      const pickKindCb = React.useCallback(function (kindId) {
        setEditing(function (e) { return e === null ? null : Object.assign({}, e, { kind: kindId }) })
      }, [])
      const cancelCb = React.useCallback(function () {
        setEditing(null)
      }, [])
      const saveEditingCb = React.useCallback(function (text, kind) {
        const e = editingRef.current
        if (e === null) return
        const t = String(text).trim()
        if (t === "") {
          setFeedback({ kind: "err", text: "批注内容为空" })
          return
        }
        const k = typeof kind === "string" ? kind : DEFAULT_KIND
        lastKindRef.current = k
        const list = annotationStore.get(sessionId, path)
        if (e.noteId === undefined) {
          const note = {
            v: 1,
            id: newNoteId(),
            ref: e.ref,
            source: e.source,
            start: e.start,
            end: e.end,
            kind: k,
            note: t,
            selStart: e.selStart, selEnd: e.selEnd, selText: e.selText
          }
          persistOrClear(list.concat([note]))
        } else {
          persistOrClear(list.map(function (n) {
            return n.id === e.noteId ? Object.assign({}, n, { note: t, kind: k, selStart: e.selStart, selEnd: e.selEnd, selText: e.selText }) : n
          }))
        }
        setEditing(null)
      }, [sessionId, path, annotationStore])
      const removeNoteCb = React.useCallback(function (noteId) {
        persistOrClear(annotationStore.get(sessionId, path).filter(function (n) { return n.id !== noteId }))
        setSelectedIds(function (ids) { return ids.filter(function (id) { return id !== noteId }) })
        setEditing(function (e) { return e !== null && e.noteId === noteId ? null : e })
      }, [sessionId, path, annotationStore])
    
      // ── free-text selection annotation ────────────────────────────────────
      function captureSelection() {
        const s = window.getSelection()
        if (s === null || s.isCollapsed || s.rangeCount === 0) return null
        const range = s.getRangeAt(0)
        function unitOf(node) {
          if (node === null) return null
          const el = node.nodeType === 3 ? node.parentElement : node
          return el === null ? null : el.closest("[data-mdan-ref]")
        }
        const unit = unitOf(range.commonAncestorContainer)
        if (unit === null) return null
        if (unitOf(s.anchorNode) !== unit || unitOf(s.focusNode) !== unit) return null
        if (unit.closest(".mdan-editor") !== null || unit.closest(".mdan-panel") !== null) return null
        let start = boundaryOffset(unit, range.startContainer, range.startOffset)
        let end = boundaryOffset(unit, range.endContainer, range.endOffset)
        if (start === null || end === null) return null
        if (start > end) { const tmp = start; start = end; end = tmp }
        const text = unit.textContent.slice(start, end)
        if (text.trim() === "") return null
        return { ref: unit.getAttribute("data-mdan-ref"), start: start, end: end, text: text, rect: range.getBoundingClientRect() }
      }
      function handleSelection() {
        const pick = captureSelection()
        if (pick === null) { setSel(null); return }
        const scrollEl = scrollRef.current
        if (scrollEl === null) { setSel(null); return }
        const sr = scrollEl.getBoundingClientRect()
        pick.x = clamp(pick.rect.left - sr.left + scrollEl.scrollLeft, 4, Math.max(4, scrollEl.clientWidth - 96))
        pick.y = clamp(pick.rect.bottom - sr.top + scrollEl.scrollTop + 6, 4, Math.max(4, scrollEl.scrollHeight - 24))
        setSel(pick)
      }
      function openSelEditor() {
        if (sel === null) return
        const d = decodeRef(sel.ref)
        const block = d === null ? undefined : blocks[d.index]
        if (block === undefined) { setSel(null); return }
        const item = d !== null && d.kind === "i" && block.type === "list" && d.item !== undefined ? block.items[d.item] : undefined
        setEditing({
          ref: sel.ref,
          source: item !== undefined ? item.source : block.source,
          start: item !== undefined ? item.start : block.start,
          end: item !== undefined ? item.end : block.end,
          kind: lastKindRef.current,
          selStart: sel.start, selEnd: sel.end, selText: sel.text,
          initialText: ""
        })
        setFeedback(null)
        setSel(null)
      }
    
      function displayPath() {
        const cwd = props.scope === undefined ? undefined : props.scope.cwd
        if (typeof cwd === "string" && typeof path === "string" && path.indexOf(cwd) === 0) {
          const rel = path.slice(cwd.length).replace(/^[/\\]+/, "")
          return rel === "" ? path : rel
        }
        return path
      }
      function excerptLines(n) {
        const source = n.selText !== undefined ? n.selText : n.source
        const s = truncate(source, 240)
        if (s.trim() === "") return ["（空内容）"]
        return s.split("\n")
      }
      function clearAll() {
        annotationStore.clear(sessionId, path)
        setTick(function (t) { return t + 1 })
        setSelectedIds([])
        setFeedback({ kind: "ok", text: "已清空" })
      }
      function togglePanel(next) {
        setPanel(function (prev) {
          const open = typeof next === "boolean" ? next : !prev.open
          if (!open) {
            const closed = Object.assign({}, prev, { open: false })
            panelPrefsStore.set(sessionId, path, closed)
            return closed
          }
          const root = rootRef.current
          const rect = root === null ? null : root.getBoundingClientRect()
          let nextPrefs = Object.assign({}, prev, { open: true })
          if (typeof nextPrefs.x !== "number" || typeof nextPrefs.y !== "number") {
            nextPrefs.x = rect === null ? 24 : rect.left + 16
            nextPrefs.y = rect === null ? 24 : rect.top + 16
          }
          nextPrefs = clampPanel(nextPrefs, window.innerWidth, window.innerHeight)
          panelPrefsStore.set(sessionId, path, nextPrefs)
          return nextPrefs
        })
      }
      function toggleBar() {
        setPanel(function (prev) {
          const nextPrefs = Object.assign({}, prev, { barCollapsed: prev.barCollapsed !== true })
          panelPrefsStore.set(sessionId, path, nextPrefs)
          return nextPrefs
        })
      }
      togglePanelRef.current = togglePanel
    
      function beginDrag(event, kind) {
        if (dragRef.current !== null) return
        const root = rootRef.current
        const rect = root === null ? null : root.getBoundingClientRect()
        const target = event.currentTarget
        if (target !== null && typeof target.setPointerCapture === "function") {
          try { target.setPointerCapture(event.pointerId) } catch (error) { console.debug("[dsh-md-annotator] setPointerCapture failed:", error) }
        }
        dragRef.current = {
          kind: kind,
          pointerId: event.pointerId,
          startClientX: event.clientX,
          startClientY: event.clientY,
          baseX: typeof panel.x === "number" ? panel.x : (rect === null ? 24 : rect.left + 16),
          baseY: typeof panel.y === "number" ? panel.y : (rect === null ? 24 : rect.top + 16),
          baseW: typeof panel.w === "number" ? panel.w : PANEL_DEFAULTS.w,
          baseH: typeof panel.h === "number" ? panel.h : PANEL_DEFAULTS.h,
          lastClientX: event.clientX,
          lastClientY: event.clientY,
          frame: null
        }
      }
      function dragGeom(d) {
        const dx = d.lastClientX - d.startClientX
        const dy = d.lastClientY - d.startClientY
        if (d.kind === "move") {
          return {
            x: clamp(d.baseX + dx, PANEL_MARGIN.x, Math.max(PANEL_MARGIN.x, window.innerWidth - PANEL_MARGIN.keepX)),
            y: clamp(d.baseY + dy, PANEL_MARGIN.y, Math.max(PANEL_MARGIN.y, window.innerHeight - PANEL_MARGIN.keepY))
          }
        }
        return {
          w: clamp(d.baseW + dx, PANEL_MIN.w, Math.max(PANEL_MIN.w, window.innerWidth - d.baseX - PANEL_MARGIN.x)),
          h: clamp(d.baseH + dy, PANEL_MIN.h, Math.max(PANEL_MIN.h, window.innerHeight - d.baseY - PANEL_MARGIN.y))
        }
      }
      function moveDrag(event) {
        const d = dragRef.current
        if (d === null || d.pointerId !== event.pointerId) return
        event.preventDefault()
        d.lastClientX = event.clientX
        d.lastClientY = event.clientY
        if (d.frame === null) {
          d.frame = requestAnimationFrame(function () {
            d.frame = null
            if (dragRef.current !== d) return
            const geom = dragGeom(d)
            setPanel(function (p) { return Object.assign({}, p, geom) })
          })
        }
      }
      function endDrag(event) {
        const d = dragRef.current
        if (d === null || d.pointerId !== event.pointerId) return
        dragRef.current = null
        if (d.frame !== null) { cancelAnimationFrame(d.frame); d.frame = null }
        const geom = dragGeom(d)
        setPanel(function (p) {
          const next = Object.assign({}, p, geom)
          panelPrefsStore.set(sessionId, path, next)
          return next
        })
      }
    
      function sendNotes(notes) {
        if (!notes || notes.length === 0) return
        const rootCtx = props.ctx
        const sessions = rootCtx !== undefined && typeof rootCtx.get === "function" ? rootCtx.get("sessions") : undefined
        const conversation = rootCtx !== undefined && typeof rootCtx.get === "function" ? rootCtx.get("conversation") : undefined
        if (sessions === undefined || conversation === undefined) {
          setFeedback({ kind: "err", text: "无法写入对话框", detail: "未找到会话输入服务" })
          return
        }
        let actx = undefined
        try { actx = sessions.scope(sessionId) } catch (error) { console.debug("[dsh-md-annotator] sessions.scope failed:", error) }
        if (actx === undefined) {
          setFeedback({ kind: "err", text: "无法写入对话框", detail: "当前会话不可用" })
          return
        }
        try {
          const input = conversation.input.for(actx)
          const current = input.state.getSnapshot().draft
          const prefix = String(pluginSetting("reportPrefix", "")).trim()
          const report = formatReport({
            notes: notes,
            prefix: prefix,
            pathLabel: displayPath(),
            excerptOf: excerptLines,
            isStale: function (n) { return n.stale === true }
          })
          input.setDraft(current.trim() === "" ? report : current + "\n\n" + report)
          const sentIds = notes.map(function (n) { return n.id })
          if (pluginSetting("clearAfterSend", true) === true) {
            persistOrClear(annotationStore.get(sessionId, path).filter(function (n) { return sentIds.indexOf(n.id) === -1 }))
            setSelectedIds(function (ids) { return ids.filter(function (id) { return sentIds.indexOf(id) === -1 }) })
            setFeedback({ kind: "ok", text: "已发送 " + notes.length + " 条", detail: "已写入对话框草稿并清空已发送批注，回车即可发送" })
          } else {
            setFeedback({ kind: "ok", text: "已发送 " + notes.length + " 条", detail: "已写入对话框草稿，批注保留，回车即可发送" })
          }
        } catch (error) {
          console.error("[dsh-md-annotator] draft insert failed:", error)
          setFeedback({ kind: "err", text: "写入失败", detail: String(error && error.message ? error.message : error) })
        }
      }
      function sendToDraft() { sendNotes(annotations) }
      function sendSelected() { sendNotes(annotations.filter(function (n) { return selectedSet.has(n.id) })) }
      function toggleSelected(noteId) {
        setSelectedIds(function (ids) {
          return ids.indexOf(noteId) === -1 ? ids.concat([noteId]) : ids.filter(function (id) { return id !== noteId })
        })
      }
      function toggleSelectAll() {
        if (annotations.length === 0) return
        const allOn = annotations.every(function (n) { return selectedSet.has(n.id) })
        setSelectedIds(allOn ? [] : annotations.map(function (n) { return n.id }))
      }
      function exportJson() {
        if (annotations.length === 0) { setFeedback({ kind: "err", text: "没有可导出的批注" }); return }
        const data = {
          plugin: "dsh-md-annotator",
          version: 1,
          exportedAt: new Date().toISOString(),
          path: path,
          sessionId: sessionId === undefined ? null : sessionId,
          notes: annotations.map(function (n) {
            return { v: n.v, id: n.id, ref: n.ref, source: n.source, start: n.start, end: n.end, kind: n.kind, note: n.note, selStart: n.selStart, selEnd: n.selEnd, selText: n.selText }
          })
        }
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = "md-annotations.json"
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
      }
    
      React.useEffect(function () {
        if (anchor === null || rootRef.current === null) return
        const el = rootRef.current.querySelector('[data-mdan-ref="' + anchor + '"]')
        if (el !== null) el.scrollIntoView({ block: "center", behavior: "smooth" })
        setAnchor(null)
      }, [anchor])
    
      // Register the Escape handler once (latest state read via refs); ignore
      // Escape while the host's own input fields are focused.
      React.useEffect(function () {
        function onKey(event) {
          if (event.key !== "Escape") return
          const t = event.target
          if (t !== null && (t.tagName === "INPUT" || t.tagName === "TEXTAREA" || t.isContentEditable === true)) return
          if (editingRef.current !== null) {
            setEditing(null)
            event.preventDefault()
            return
          }
          if (selRef.current !== null) {
            setSel(null)
            event.preventDefault()
            return
          }
          if (panelOpenRef.current === true) {
            togglePanelRef.current(false)
            event.preventDefault()
          }
        }
        window.addEventListener("keydown", onKey)
        return function () { window.removeEventListener("keydown", onKey) }
      }, [])
    
      // Paint text-selection ranges through CSS Custom Highlight. Degrades to
      // chips-only without CSS.highlights. One DOM pass builds the ref→element map.
      React.useEffect(function () {
        const canHighlight = typeof CSS !== "undefined" && CSS.highlights !== undefined && typeof Highlight === "function"
        if (!canHighlight) return undefined
        if (rootRef.current === null) return undefined
        const elByRef = new Map()
        rootRef.current.querySelectorAll("[data-mdan-ref]").forEach(function (el) {
          elByRef.set(el.getAttribute("data-mdan-ref"), el)
        })
        const ranges = []
        annotations.forEach(function (n) {
          if (n.selStart === undefined || n.selEnd === undefined) return
          const el = elByRef.get(n.ref)
          if (el === undefined) return
          let s = n.selStart
          let e = n.selEnd
          if (el.textContent.slice(s, e) !== n.selText) {
            const idx = el.textContent.indexOf(n.selText)
            if (idx === -1) return
            s = idx
            e = idx + n.selText.length
          }
          const r = rangeFromOffsets(el, s, e)
          if (r !== null) ranges.push(r)
        })
        if (ranges.length === 0) CSS.highlights.delete("mdan-sel")
        else CSS.highlights.set("mdan-sel", new Highlight(...ranges))
        return function () { CSS.highlights.delete("mdan-sel") }
      }, [annotations, blocks])
    
      // Pull a floating panel back into the viewport on window resize (RAF-throttled).
      React.useEffect(function () {
        let frame = null
        function onResize() {
          if (panelOpenRef.current !== true) return
          if (frame !== null) return
          frame = requestAnimationFrame(function () {
            frame = null
            setPanel(function (p) {
              if (p.open !== true || typeof p.x !== "number" || typeof p.y !== "number") return p
              const next = clampPanel(p, window.innerWidth, window.innerHeight)
              if (next.x === p.x && next.y === p.y && next.w === p.w && next.h === p.h) return p
              panelPrefsStore.set(sessionId, path, next)
              return next
            })
          })
        }
        window.addEventListener("resize", onResize)
        return function () {
          window.removeEventListener("resize", onResize)
          if (frame !== null) cancelAnimationFrame(frame)
        }
      }, [sessionId, path, panelPrefsStore])
    
      function renderListPanel() {
        const allOn = annotations.length > 0 && annotations.every(function (n) { return selectedSet.has(n.id) })
        let selectedCount = 0
        annotations.forEach(function (n) { if (selectedSet.has(n.id)) selectedCount++ })
        const rows = annotations.map(function (n, k) {
          const checked = selectedSet.has(n.id)
          return React.createElement("div", { key: n.id, className: "mdan-row" },
            React.createElement("input", {
              type: "checkbox",
              className: "mdan-row-check",
              checked: checked,
              title: checked ? "取消勾选" : "勾选这条",
              "aria-label": checked ? "取消勾选" : "勾选这条",
              onChange: function () { toggleSelected(n.id) }
            }),
            React.createElement("button", {
              type: "button",
              className: "mdan-row-jump",
              title: "定位到原文",
              "aria-label": "定位到原文",
              onClick: function () { setAnchor(n.ref) }
            }, String(k + 1) + "."),
            React.createElement("div", { className: "mdan-row-body" },
              kindTag(n.kind),
              React.createElement("div", { className: "mdan-row-note" }, n.note),
              React.createElement("div", { className: "mdan-row-quote" }, (n.selText !== undefined ? "选中：" + truncate(n.selText, 120) : "原文：" + truncate(n.source, 120)) + (n.stale === true ? "（原文已变化）" : ""))),
            React.createElement("button", {
              type: "button",
              className: "mdan-icon-btn",
              title: "发送这条到对话框",
              "aria-label": "发送这条到对话框",
              onClick: function () { sendNotes([n]) }
            }, "➤"),
            React.createElement("button", {
              type: "button",
              className: "mdan-note-btn",
              title: "移除这条批注",
              "aria-label": "移除这条批注",
              onClick: function () { removeNoteCb(n.id) }
            }, "移除"))
        })
        const style = {
          left: (typeof panel.x === "number" ? panel.x : 16) + "px",
          top: (typeof panel.y === "number" ? panel.y : 16) + "px",
          width: (typeof panel.w === "number" ? panel.w : PANEL_DEFAULTS.w) + "px",
          height: (typeof panel.h === "number" ? panel.h : PANEL_DEFAULTS.h) + "px"
        }
        return React.createElement("div", { className: "mdan-panel", style: style, role: "dialog", "aria-label": "批注清单" },
          React.createElement("div", {
            className: "mdan-panel-head",
            onPointerDown: function (event) { beginDrag(event, "move") },
            onPointerMove: moveDrag,
            onPointerUp: endDrag,
            onPointerCancel: endDrag,
            onLostPointerCapture: endDrag
          },
            React.createElement("span", { className: "mdan-panel-title", title: "拖动标题栏可移动" }, "批注清单"),
            React.createElement("button", {
              type: "button",
              className: "mdan-icon-btn",
              title: allOn ? "取消全选" : "全选",
              "aria-label": allOn ? "取消全选" : "全选",
              disabled: annotations.length === 0,
              onPointerDown: function (event) { event.stopPropagation() },
              onMouseDown: function (event) { event.stopPropagation() },
              onClick: toggleSelectAll
            }, allOn ? "☐" : "☑"),
            React.createElement("button", {
              type: "button",
              className: "mdan-icon-btn",
              title: selectedCount > 0 ? "发送所选项到对话框（" + selectedCount + "）" : "发送所选项到对话框",
              "aria-label": "发送所选项到对话框",
              disabled: selectedCount === 0,
              onPointerDown: function (event) { event.stopPropagation() },
              onMouseDown: function (event) { event.stopPropagation() },
              onClick: sendSelected
            }, "➤"),
            React.createElement("button", {
              type: "button",
              className: "mdan-note-btn",
              disabled: annotations.length === 0,
              onPointerDown: function (event) { event.stopPropagation() },
              onMouseDown: function (event) { event.stopPropagation() },
              onClick: clearAll
            }, "清空全部"),
            React.createElement("button", {
              type: "button",
              className: "mdan-note-btn",
              title: "导出为 JSON",
              "aria-label": "导出为 JSON",
              disabled: annotations.length === 0,
              onPointerDown: function (event) { event.stopPropagation() },
              onMouseDown: function (event) { event.stopPropagation() },
              onClick: exportJson
            }, "导出"),
            React.createElement("button", {
              type: "button",
              className: "mdan-note-btn",
              "aria-label": "关闭清单",
              onPointerDown: function (event) { event.stopPropagation() },
              onMouseDown: function (event) { event.stopPropagation() },
              onClick: function () { togglePanel(false) }
            }, "关闭")),
          React.createElement("div", { className: "mdan-panel-body" },
            rows.length === 0
              ? React.createElement("div", { className: "mdan-empty" }, "还没有批注。悬停段落点「＋批注」，或拖选文字点「＋批注选区」。")
              : rows),
          React.createElement("div", {
            className: "mdan-panel-resize",
            title: "拖动调整大小",
            "aria-label": "拖动调整大小",
            onPointerDown: function (event) { event.stopPropagation(); beginDrag(event, "resize") },
            onPointerMove: moveDrag,
            onPointerUp: endDrag,
            onPointerCancel: endDrag,
            onLostPointerCapture: endDrag
          }))
      }
    
      function renderBar() {
        const collapsed = panel.barCollapsed === true
        return React.createElement("div", { className: "mdan-bar" + (collapsed ? " mdan-bar-collapsed" : "") },
          React.createElement("button", {
            type: "button",
            className: "mdan-bar-handle",
            title: collapsed ? "展开批注栏" : "收起批注栏",
            "aria-label": collapsed ? "展开批注栏" : "收起批注栏",
            onClick: toggleBar
          }, collapsed ? "︿" : "﹀"),
          React.createElement("div", { className: "mdan-bar-body" },
            React.createElement("span", { className: "mdan-bar-count" }, "共 " + annotations.length + " 条批注"),
            React.createElement("button", {
              type: "button",
              className: "mdan-btn",
              onClick: function () { togglePanel() }
            }, panel.open ? "收起清单" : "批注清单"),
            React.createElement("button", {
              type: "button",
              className: "mdan-btn",
              disabled: annotations.length === 0,
              onClick: clearAll
            }, "清空"),
            React.createElement("button", {
              type: "button",
              className: "mdan-btn",
              disabled: annotations.length === 0,
              onClick: exportJson
            }, "导出"),
            React.createElement("button", {
              type: "button",
              className: "mdan-btn mdan-btn-primary",
              disabled: annotations.length === 0,
              onClick: sendToDraft
            }, "全部发送"),
            feedback !== null ? React.createElement("span", {
              className: "mdan-feedback" + (feedback.kind === "err" ? " mdan-feedback-err" : ""),
              title: feedback.detail !== undefined ? feedback.detail : feedback.text
            }, feedback.text) : null))
      }
    
      const body = blocks.map(function (block, index) {
        const ref = encodeRef(index, undefined, refIndex.blockSigs[index])
        const blockNotes = notesByRef.get(ref) || []
        return React.createElement(MdBlock, {
          key: "b" + index,
          block: block,
          index: index,
          refIndex: refIndex,
          notesByRef: notesByRef,
          notes: blockNotes,
          editing: editing,
          onOpenBlock: openEditorCb,
          onEdit: openEditorForCb,
          onRemove: removeNoteCb,
          onPickKind: pickKindCb,
          onSave: saveEditingCb,
          onCancel: cancelCb
        })
      })
    
      const rootClass = "mdan-root"
        + (sel !== null ? " mdan-selecting" : "")
        + (editing !== null ? " mdan-editing" : "")
      return React.createElement("div", { className: rootClass, ref: rootRef, onMouseUp: function () { handleSelection() } },
        React.createElement("div", { className: "mdan-scroll", ref: scrollRef },
          props.truncated === true ? React.createElement("div", { className: "mdan-banner" }, "文件过大，仅预览截断内容") : null,
          content === undefined ? React.createElement("div", { className: "mdan-loading" }, "加载中…") : null,
          content !== undefined && blocks.length === 0 ? React.createElement("div", { className: "mdan-empty" }, "（空文档）") : null,
          body,
          sel !== null ? React.createElement("button", {
            type: "button",
            className: "mdan-selpick",
            style: { left: sel.x + "px", top: sel.y + "px" },
            title: "针对选中的文字添加批注",
            "aria-label": "针对选中的文字添加批注",
            onMouseDown: function (event) { event.preventDefault(); event.stopPropagation() },
            onClick: function () { openSelEditor() }
          }, "＋ 批注选区（" + sel.text.length + " 字）") : null),
        panel.open ? renderListPanel() : null,
        renderBar())
    }
    
    //#endregion
    //#region src/entry.js
    // ── plugin ──────────────────────────────────────────────────────────────
    const inject = ["betterSidebar", "conversation", "sessions"]
    
    function apply(context) {
      const sidebar = context.betterSidebar
      // Per-activation stores (no module-level singleton): the viewer receives
      // them via props, keeping storage lifetime tied to the plugin activation.
      const annotationStore = createAnnotationStore()
      const panelPrefsStore = createPanelPrefsStore()
      context.effect(function () {
        const supportsPluginSettings = Array.isArray(sidebar.features) && sidebar.features.indexOf("pluginSettings") !== -1
        return sidebar.registerFileViewer({
          id: "md-annotator",
          title: "MD 批注预览",
          icon: function (size) {
            return React.createElement("span", { style: { fontSize: Math.max(12, Number(size) || 12) + "px", lineHeight: 1 } }, "✍")
          },
          exts: ["md", "markdown"],
          priority: 10,
          fetchStrategy: "fsRead",
          settings: supportsPluginSettings ? {
            pluginToggles: [
              { key: "clearAfterSend", title: "发送后自动清空批注", desc: "把批注写入对话框后自动清空本文件批注（默认开启；关闭后批注跨轮累积，每次发送都会带上全部历史批注）", type: "switch" },
              { key: "reportPrefix", title: "发送内容前缀", desc: "附加在批注内容开头的说明文字", type: "text", placeholder: "（可选）例如：请逐项修改并保持原有语气" }
            ]
          } : undefined,
          component: function (props) {
            return React.createElement(MdErrorBoundary, null,
              React.createElement(MdAnnotateView, Object.assign({}, props, { annotationStore: annotationStore, panelPrefsStore: panelPrefsStore })))
          }
        })
      })
    }
    
    exports.apply = apply
    exports.inject = inject
    // Test hook (smoke/unit tests materialize the factory under Node with a stub
    // require("react"); the browser never reads this export).
    exports._test = {
      parseBlocks: parseBlocks,
      renderInline: renderInline,
      parseTable: parseTable,
      resolveSource: resolveSource,
      encodeRef: encodeRef,
      decodeRef: decodeRef,
      hashSource: hashSource,
      buildRefIndex: buildRefIndex,
      reanchorNotes: reanchorNotes,
      formatReport: formatReport,
      createAnnotationStore: createAnnotationStore,
      createPanelPrefsStore: createPanelPrefsStore,
      storeKey: storeKey,
      clamp: clamp,
      truncate: truncate
    }
    
    //#endregion
    return module.exports
  }
})
